/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroupDispatcher: typeof import('element-plus/es')['ElCheckboxGroupDispatcher']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePickerDispatcher: typeof import('element-plus/es')['ElDatePickerDispatcher']
    ElFormDispatcher: typeof import('element-plus/es')['ElFormDispatcher']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInputDispatcher: typeof import('element-plus/es')['ElInputDispatcher']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroupDispatcher: typeof import('element-plus/es')['ElRadioGroupDispatcher']
    ElSelectDispatcher: typeof import('element-plus/es')['ElSelectDispatcher']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElSwitchDispatcher: typeof import('element-plus/es')['ElSwitchDispatcher']
    ElTimePickerDispatcher: typeof import('element-plus/es')['ElTimePickerDispatcher']
    FormView: typeof import('./src/components/FormView.vue')['default']
  }
}
