/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElCheckboxDispatcher: typeof import('element-plus-form-dispatcher')['ElCheckboxDispatcher']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInputDispatcher: typeof import('element-plus-form-dispatcher')['ElInputDispatcher']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElSwitchDispatcher: typeof import('element-plus-form-dispatcher')['ElSwitchDispatcher']
    FormView: typeof import('./src/components/FormView.vue')['default']
  }
}

// For TSX support
declare global {
  const ElCheckboxDispatcher: typeof import('element-plus-form-dispatcher')['ElCheckboxDispatcher']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInputDispatcher: typeof import('element-plus-form-dispatcher')['ElInputDispatcher']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElSwitchDispatcher: typeof import('element-plus-form-dispatcher')['ElSwitchDispatcher']
  const FormView: typeof import('./src/components/FormView.vue')['default']
}