/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInputDispatcher: typeof import('element-plus-form-dispatcher')['ElInputDispatcher']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FormView: typeof import('./src/components/FormView.vue')['default']
  }
}
